### ISSUE TITLE
关于异步接口的接口编写

### ISSUE THREAD

**Issue by GitHubForBai** [dearKundy/excel-utils#1]
老哥你好，想详细咨询一下关于异步接口的编写方式,还是不太理解这个模式
1、编写异步接口
2、编写excel状态接口
3、编写从服务器本地返回excel文件接口

**Comment by dearKundy** [comment]
一、后端提供以下三个接口：
1. 异步任务请求接口：该接口负责新建 excel 导出任务到服务器本地，并直接异步生成任务唯一标识返回前端，这时候虽然 excel 正在生成过程中，但是通过异步的方式，可以直接返回唯一标识。
2. excel 导出状态接口：该接口负责根据任务的唯一标识查询服务器本地的 excel 文件是否生成成功，也就是检查 excel 文件是否存在。
3. excel 文件下载接口：该接口负责返回生成的 excel 文件。

二、前端流程：
1. 请求异步任务请求接口，保存唯一标识。
2. 使用唯一标识轮询excel导出状态接口，假如返回成功，则进行第3步，否则继续轮询。
3. 假如第二步中的接口返回成功，则请求 excel 文件下载接口，即可成功拿到结果。

如果对于细节还有不明白的地方，可以继续提出来哦~
