### ISSUE TITLE
当集合为空情况下，会报空指针

### ISSUE THREAD

**Issue by RainorshineGW** [dearKundy/excel-utils#4]
1.使用反射获取集合中第一个数据的对象时，如果集合中没有数据为空会报空指针
2.导出的数据，需要对象中的字段顺序与excel定义的字段顺序一致，这点体验不太好

**Comment by zhuxl13817468272** [comment]
空指针异常主要问题解决：在ExcelUtils类中的getWorkbook方法，增加一段逻辑判断查出来的数据为空时datas.length == 0，执行创建只带有表头而没有内容的sheet返回。
 if (datas.length == 0){
            Sheet sheet1 = workbook.createSheet("空数据");
            pageRowNum = 0; // 行号重置为0
            for (int j = 0; j <= getHeaderRowNum(excelHeaderInfos); j++) { //遍历数据的总行数
                sheet1.createRow(pageRowNum++);
            }
            createHeader(sheet1, style); // 设置表单表头
            return workbook;
        }

**Comment by zhuxl13817468272** [comment]
当数据不为空的时候代码如下：
 for (int i = 0; i < datas.length; i++) {
            if (i % SHEET_MAX_ROW == 0) {  // 如果是每个sheet的首行
                //创建新的sheet
                sheet = createSheet(workbook, i);
                //创建表头
                pageRowNum = 0; // 行号重置为0
                for (int j = 0; j < getHeaderRowNum(excelHeaderInfos); j++) { //遍历数据的总行数
                    sheet.createRow(pageRowNum++);
                }
                createHeader(sheet, style); // 设置表单表头
                // 创建内容
                Row row = sheet.createRow(pageRowNum++);
                createContent(row, style, datas, i, list.get(0).getClass().getDeclaredFields());  //创建表单正文
            }
        }

**Comment by zhuxl13817468272** [comment]
空指针报错问题解决，然后在优化，当查询出来的数据为空时，只导出表头而没有内容。优化后的ExcelUtils的getWorkbook完整方法如下：
 public Workbook getWorkbook() {
        Workbook workbook = new SXSSFWorkbook(ROW_ACCESS_WINDOW_SIZE); //workbook 空的即将创建的工作簿
        String[][] datas = transformData(); //获取要导出的数据  datas[i][j]表示 i行数据的第j列的值
//        Field[] fields = list.get(0).getClass().getDeclaredFields(); //eg: private java.lang.Long com.kundy.excelutils.entity.po.TtlProductInfoPo.id
        CellStyle style = setCellStyle(workbook); //单元格样式
        int pageRowNum = 0;
        Sheet sheet = null;

        long startTime = System.currentTimeMillis();
        LOGGER.info("开始处理excel文件。。。");

        //处理查出来的数据为空时
        if (datas.length == 0){
            //创建新的sheet
            Sheet sheet1 = workbook.createSheet("空数据");
            //创建表头
            pageRowNum = 0; // 行号重置为0
            for (int j = 0; j <= getHeaderRowNum(excelHeaderInfos); j++) { //遍历数据的总行数
                sheet1.createRow(pageRowNum++);
            }
            createHeader(sheet1, style); // 设置表单表头
            return workbook;
        }

        //查询数据不为空（至少有一条）
        for (int i = 0; i < datas.length; i++) {
            if (i % SHEET_MAX_ROW == 0) {  // 如果是每个sheet的首行
                //创建新的sheet
                sheet = createSheet(workbook, i);
                //创建表头
                pageRowNum = 0; // 行号重置为0
                for (int j = 0; j < getHeaderRowNum(excelHeaderInfos); j++) { //遍历数据的总行数
                    sheet.createRow(pageRowNum++);
                }
                createHeader(sheet, style); // 设置表单表头
                // 创建内容
                Row row = sheet.createRow(pageRowNum++);
                createContent(row, style, datas, i, list.get(0).getClass().getDeclaredFields());  //创建表单正文
            }
        }

        LOGGER.info("处理文本耗时" + (System.currentTimeMillis() - startTime) + "ms");
        return workbook;
    }

**Comment by zhuxl13817468272** [comment]
空指针报错解决 + 空数据时只导出表头优化 。完整ExcelUtils的getWorkbook如下：
  /**
     *  创建工作簿
     * @return  返回含表头+内容的工作簿
     */
    public Workbook getWorkbook() {
        Workbook workbook = new SXSSFWorkbook(ROW_ACCESS_WINDOW_SIZE); //workbook 空的即将创建的工作簿
        String[][] datas = transformData(); //获取要导出的数据  datas[i][j]表示 i行数据的第j列的值
//        Field[] fields = list.get(0).getClass().getDeclaredFields(); //eg: private java.lang.Long com.kundy.excelutils.entity.po.TtlProductInfoPo.id
        CellStyle style = setCellStyle(workbook); //单元格样式
        int pageRowNum = 0;
        Sheet sheet = null;

        long startTime = System.currentTimeMillis();
        LOGGER.info("开始处理excel文件。。。");

        //处理查出来的数据为空时
        if (datas.length == 0){
            //创建新的sheet
            Sheet sheet1 = workbook.createSheet("空数据");
            //创建表头
            pageRowNum = 0; // 行号重置为0
            for (int j = 0; j <= getHeaderRowNum(excelHeaderInfos); j++) { //遍历数据的总行数
                sheet1.createRow(pageRowNum++);
            }
            createHeader(sheet1, style); // 设置表单表头
            return workbook;
        }

        //查询数据不为空（至少有一条）
        for (int i = 0; i < datas.length; i++) {
            if (i % SHEET_MAX_ROW == 0) {  // 如果是每个sheet的首行
                //创建新的sheet
                sheet = createSheet(workbook, i);
                //创建表头
                pageRowNum = 0; // 行号重置为0
                for (int j = 0; j < getHeaderRowNum(excelHeaderInfos); j++) { //遍历数据的总行数
                    sheet.createRow(pageRowNum++);
                }
                createHeader(sheet, style); // 设置表单表头

            }
            // 创建内容
            Row row = sheet.createRow(pageRowNum++);
            createContent(row, style, datas, i, list.get(0).getClass().getDeclaredFields());  //创建表单正文
        }

        LOGGER.info("处理文本耗时" + (System.currentTimeMillis() - startTime) + "ms");
        return workbook;
    }
